### ISSUE TITLE
Match Strategy Missing?

### ISSUE THREAD

**Issue by ForteUnited** [smartystreets/smartystreets-csharp-sdk#2]
I've taken a look at the current client and lookup objects for the US Street Address API and I can't seem to find anything to lines up with the Match Strategy parameter in the API documentation. Am I missing something?

**Comment by mdwhatcott** [comment]
You are correct, it is currently missing. we plan to add it.

**Comment by mdwhatcott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [C# SDK: add Lookup.Match field](https://trello.com/c/mIAbXbik/1672-c-sdk-add-lookup-match-field)

**Comment by ForteUnited** [comment]
Ok. I haven't gone and looked at the source but can I assume that it is using the default Match Strategy of "scrict"?

**Comment by mdwhatcott** [comment]
Yes, when no match strategy is specified the default strategy is "strict".

**Comment by Jmaur** [comment]
@mdwhatcott this issue still hasn't been fixed.

**Comment by mdwhatcott** [comment]
@Jmaur - Actually, it has!

The MatchStrategy field has already been added to the Lookup:

https://github.com/smartystreets/smartystreets-dotnet-sdk/blob/master/src/sdk/USStreetApi/Lookup.cs#L51

It has three possible values:

https://github.com/smartystreets/smartystreets-dotnet-sdk/blob/master/src/sdk/USStreetApi/Lookup.cs#L12

**Comment by Jmaur** [comment]
@mdwhatcott it was added to the Lookup class but it was not added to the PopulateQueryString method of the Client.cs class which maps the address fields to the request parameters.

https://github.com/smartystreets/smartystreets-dotnet-sdk/blob/master/src/sdk/USStreetApi/Client.cs#L68

**Comment by mdwhatcott** [comment]
Should be fixed with 79c6b069e054b7052d4fd185acf701403f91c69c

Thanks for your help @Jmaur

**Comment by Jmaur** [comment]
No problem @mdwhatcott glad to help, do you know when the nuget package will be updated?

**Comment by mdwhatcott** [comment]
Probably sometime in the next few days.
